export const SERVICES_CATALOG = [
  {
    id: "floors",
    name: "Полы",
    icon: "⬛",
    image: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800&q=80",
    subcategories: [
      {
        id: "floors_rough",
        name: "Черновые работы",
        image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
        items: [
          { name: "Стяжка бетонная", price: "1200 ₽/м²" },
          { name: "Стяжка ручная", price: "900 ₽/м²" },
          { name: "Механизированная стяжка", price: "1200 ₽/м²" },
          { name: "Наливной пол", price: "400 ₽/м²" },
          { name: "Выравнивание пола", price: "450 ₽/м²" },
          { name: "Шумоизоляция пола", price: "300 ₽/м²" },
          { name: "Гидроизоляция пола", price: "250 ₽/м²" },
          { name: "Монтаж теплого пола", price: "600 ₽/м²" },
        ],
      },
      {
        id: "floors_finish",
        name: "Чистовые покрытия",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
        items: [
          { name: "Ламинат", price: "600 ₽/м²" },
          { name: "Кварцвинил", price: "800 ₽/м²" },
          { name: "Линолеум", price: "450 ₽/м²" },
          { name: "Коммерческий линолеум", price: "700 ₽/м²" },
          { name: "Паркет", price: "900 ₽/м²" },
          { name: "Шлифовка паркета", price: "350 ₽/м²" },
          { name: "Лакировка паркета", price: "400 ₽/м²" },
        ],
      },
      {
        id: "floors_plinth",
        name: "Плинтуса",
        image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
        items: [
          { name: "ПВХ", price: "200 ₽/м.п" },
          { name: "МДФ", price: "350 ₽/м.п" },
          { name: "Дерево", price: "400 ₽/м.п" },
        ],
      },
    ],
  },
  {
    id: "walls",
    name: "Стены",
    icon: "🧱",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80",
    subcategories: [
      {
        id: "walls_plaster",
        name: "Штукатурные работы",
        image: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80",
        items: [
          { name: "Грунтовка", price: "80 ₽/м²" },
          { name: "Бетоноконтакт", price: "150 ₽/м²" },
          { name: "Кварцгрунт", price: "150 ₽/м²" },
          { name: "Гипсовая штукатурка", price: "800 ₽/м²" },
          { name: "Цементная штукатурка", price: "1000 ₽/м²" },
          { name: "Безмаячная штукатурка", price: "450 ₽/м²" },
          { name: "Армирование сеткой", price: "120 ₽/м²" },
          { name: "Штукатурка откосов", price: "500 ₽/м.п" },
          { name: "Установка малярного угла", price: "150 ₽/м.п" },
        ],
      },
      {
        id: "walls_painting",
        name: "Малярные работы",
        image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80",
        items: [
          { name: "Шпаклевка под обои", price: "550 ₽/м²" },
          { name: "Шпаклевка под покраску", price: "1050 ₽/м²" },
          { name: "Шлифовка", price: "120 ₽/м²" },
          { name: "Поклейка стеклохолста стены", price: "200 ₽/м²" },
          { name: "Поклейка стеклохолста потолок", price: "300 ₽/м²" },
          { name: "Покраска стен", price: "250 ₽/м²" },
          { name: "Покраска потолка", price: "400 ₽/м²" },
          { name: "Покраска откосов", price: "700 ₽/м.п" },
          { name: "Покраска радиаторов", price: "800 ₽/шт" },
          { name: "Покраска труб", price: "250 ₽/м.п" },
          { name: "Покраска дверей", price: "1500 ₽/шт" },
        ],
      },
      {
        id: "walls_wallpaper",
        name: "Обои",
        image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80",
        items: [
          { name: "Поклейка без подбора", price: "250 ₽/м²" },
          { name: "Поклейка с подбором", price: "350 ₽/м²" },
          { name: "Флизелиновые", price: "320 ₽/м²" },
          { name: "Виниловые", price: "350 ₽/м²" },
          { name: "Фотообои", price: "500 ₽/м²" },
        ],
      },
    ],
  },
  {
    id: "tiles",
    name: "Плитка",
    icon: "🟦",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    direct: true,
    items: [
      { name: "300×300", price: "1600 ₽/м²" },
      { name: "400×400", price: "1600 ₽/м²" },
      { name: "600×600", price: "2200 ₽/м²" },
      { name: "1200×600", price: "2500 ₽/м²" },
      { name: "1800×1200", price: "3500 ₽/м²" },
      { name: "3000×1200", price: "5500 ₽/м²" },
      { name: "Мозаика", price: "3500–5000 ₽/м²" },
      { name: "Укладка «ёлкой»", price: "2500 ₽/м²" },
      { name: "Диагональная укладка", price: "+20 %" },
      { name: "Крупноформатная плитка", price: "+30 %" },
      { name: "Запил 45°", price: "1500 ₽/м.п" },
      { name: "Подрезка плитки", price: "300 ₽/м.п" },
      { name: "Отверстие под трубы", price: "800 ₽/шт" },
      { name: "Отверстие под канализацию", price: "1500 ₽/шт" },
      { name: "Люк сантехнический", price: "1500–4500 ₽" },
      { name: "Эпоксидная затирка", price: "800 ₽/м²" },
      { name: "Фартук кухни", price: "2500 ₽/м²" },
    ],
  },
  {
    id: "electric",
    name: "Электрика",
    icon: "⚡",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
    direct: true,
    items: [
      { name: "Розетка", price: "350 ₽" },
      { name: "Выключатель", price: "350 ₽" },
      { name: "Двойная розетка", price: "450 ₽" },
      { name: "Интернет / ТВ", price: "400 ₽" },
      { name: "Монтаж люстры", price: "800 ₽" },
      { name: "Точечный светильник", price: "400 ₽" },
      { name: "Светодиодная лента", price: "400 ₽/м" },
      { name: "Штробление", price: "500 ₽/м" },
      { name: "Прокладка кабеля", price: "120 ₽/м" },
      { name: "Сборка электрощита", price: "5000 ₽" },
      { name: "Замена автомата", price: "500 ₽" },
      { name: "Монтаж терморегулятора теплого пола", price: "1500 ₽" },
      { name: "Датчик движения", price: "1500 ₽" },
    ],
  },
  {
    id: "plumbing",
    name: "Сантехника",
    icon: "🚿",
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80",
    subcategories: [
      {
        id: "plumbing_main",
        name: "Сантехника",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
        items: [
          { name: "Монтаж инсталляции", price: "6000 ₽" },
          { name: "Установка унитаза", price: "2 500 ₽" },
          { name: "Установка раковины", price: "2 500 ₽" },
          { name: "Установка смесителя", price: "700 ₽" },
          { name: "Установка ванны", price: "от 5 000 ₽" },
          { name: "Установка душевой кабины", price: "7 000 ₽" },
          { name: "Разводка воды", price: "1 500 ₽/точка" },
          { name: "Разводка канализации", price: "1 200 ₽/точка" },
          { name: "Монтаж коллектора", price: "8 000 ₽" },
          { name: "Монтаж фильтра", price: "2 000 ₽" },
          { name: "Монтаж гигиенического душа", price: "2 000 ₽" },
        ],
      },
      {
        id: "plumbing_shower",
        name: "Душевые и поддоны",
        image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
        items: [
          { name: "Поддон из кирпича", price: "30 000 ₽" },
          { name: "Поддон конверт", price: "25 000 ₽" },
          { name: "Монтаж трапа", price: "4 000 ₽" },
          { name: "Монтаж ограждения", price: "5 000 ₽" },
          { name: "Формирование поддона с уклоном", price: "25 000–30 000 ₽" },
        ],
      },
    ],
  },
  {
    id: "doors",
    name: "Двери и окна",
    icon: "🚪",
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&q=80",
    direct: true,
    items: [
      { name: "Межкомнатная дверь", price: "от 3500 ₽" },
      { name: "Скрытая дверь", price: "10 000 ₽" },
      { name: "Врезка замка", price: "1 200 ₽" },
      { name: "Установка ручек", price: "400 ₽" },
      { name: "Доборы", price: "800 ₽" },
      { name: "Наличники", price: "600 ₽" },
    ],
  },
  {
    id: "demolition",
    name: "Демонтаж",
    icon: "🔨",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    direct: true,
    items: [
      { name: "Демонтаж обоев", price: "120 ₽/м²" },
      { name: "Демонтаж краски", price: "180 ₽/м²" },
      { name: "Демонтаж декоративной штукатурки", price: "250 ₽/м²" },
      { name: "Демонтаж плитки", price: "350 ₽/м²" },
      { name: "Демонтаж ПВХ панелей", price: "200 ₽/м²" },
      { name: "Демонтаж гипсокартона", price: "250 ₽/м²" },
      { name: "Демонтаж ламината", price: "150 ₽/м²" },
      { name: "Демонтаж линолеума", price: "120 ₽/м²" },
      { name: "Демонтаж паркета", price: "250 ₽/м²" },
      { name: "Демонтаж плитки пола", price: "350 ₽/м²" },
      { name: "Демонтаж стяжки", price: "600 ₽/м²" },
      { name: "Демонтаж натяжного потолка", price: "150 ₽/м²" },
      { name: "Демонтаж подвесного потолка", price: "200 ₽/м²" },
      { name: "Демонтаж потолка ГКЛ", price: "250 ₽/м²" },
      { name: "Демонтаж плинтуса", price: "80 ₽/м.п" },
      { name: "Демонтаж двери", price: "700 ₽/шт" },
      { name: "Демонтаж сантехники", price: "800 ₽/шт" },
      { name: "Демонтаж подоконника", price: "300 ₽/м.п" },
      { name: "Демонтаж перегородок", price: "650 ₽/м²" },
      { name: "Демонтаж радиатора", price: "1500 ₽/шт" },
    ],
  },
  {
    id: "drywall",
    name: "Гипсокартон",
    icon: "⬜",
    image: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=800&q=80",
    direct: true,
    items: [
      { name: "Перегородка с шумоизоляцией", price: "2000 ₽/м²" },
      { name: "Потолок ГКЛ", price: "2000 ₽/м²" },
      { name: "Потолок двойной", price: "3000 ₽/м²" },
      { name: "Короб ГКЛ", price: "1300 ₽/м.п" },
      { name: "Короб под трубы", price: "1500 ₽/м.п" },
      { name: "Короб под инсталляцию", price: "6000 ₽" },
      { name: "Короб под вытяжку", price: "2000 ₽" },
      { name: "Отверстие под светильник", price: "250 ₽" },
      { name: "Заделка швов", price: "120 ₽/м.п" },
    ],
  },
  {
    id: "ceiling",
    name: "Потолки",
    icon: "🏠",
    image: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80",
    direct: true,
    items: [
      { name: "Натяжной матовый", price: "600 ₽/м²" },
      { name: "Натяжной глянцевый", price: "600 ₽/м²" },
      { name: "Натяжной сатиновый", price: "600 ₽/м²" },
      { name: "Натяжной тканевый", price: "900 ₽/м²" },
      { name: "Парящий потолок", price: "900 ₽/м.п" },
      { name: "Монтаж профиля", price: "180 ₽/м.п" },
      { name: "Обвод трубы", price: "300 ₽" },
    ],
  },
  {
    id: "balcony",
    name: "Балконы и лоджии",
    icon: "🏡",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    direct: true,
    items: [
      { name: "Демонтаж отделки", price: "350 ₽/м²" },
      { name: "Утепление пеноплекс", price: "450 ₽/м²" },
      { name: "Утепление минвата", price: "500 ₽/м²" },
      { name: "Пароизоляция", price: "120 ₽/м²" },
      { name: "ПВХ панели", price: "750 ₽/м²" },
      { name: "МДФ панели", price: "850 ₽/м²" },
      { name: "Вагонка", price: "900 ₽/м²" },
      { name: "Декоративная штукатурка", price: "950 ₽/м²" },
      { name: "Покраска", price: "250 ₽/м²" },
      { name: "Стяжка", price: "650 ₽/м²" },
      { name: "Ламинат", price: "450 ₽/м²" },
      { name: "Плитка", price: "1200 ₽/м²" },
      { name: "Установка подоконника", price: "900 ₽/м.п" },
      { name: "Монтаж сушилки", price: "800 ₽/шт" },
      { name: "Монтаж шкафа", price: "3 500 ₽" },
    ],
  },
  {
    id: "turnkey",
    name: "Ремонт под ключ",
    icon: "🏗️",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    direct: true,
    items: [
      { name: "Косметический", price: "от 4 500 ₽/м²" },
      { name: "Капитальный", price: "от 7 000 ₽/м²" },
      { name: "Под ключ", price: "от 9 000 ₽/м²" },
      { name: "Санузел под ключ", price: "от 120 000 ₽" },
      { name: "Маленький санузел (коэф.)", price: "+20 %" },
      { name: "Крупная плитка (коэф.)", price: "+30 %" },
      { name: "Диагональная укладка (коэф.)", price: "+20 %" },
      { name: "Сложная геометрия (коэф.)", price: "+20 %" },
    ],
  },
  {
    id: "metal",
    name: "Металлоконструкции и строительство",
    icon: "🔥",
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
    subcategories: [
      {
        id: "metal_welding",
        name: "Сварочные работы",
        image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
        items: [
          { name: "Сварочные работы", price: "от 1 500 ₽" },
          { name: "Аргоновая сварка", price: "от 1 300 ₽" },
          { name: "Точечная сварка", price: "от 970 ₽" },
          { name: "Сварка труб", price: "от 1 820 ₽" },
          { name: "Монтаж металлоконструкций", price: "от 2 330 ₽" },
          { name: "Изготовление металлоконструкций", price: "от 1 200 ₽/т" },
          { name: "Изготовление ворот", price: "от 6 300 ₽" },
        ],
      },
      {
        id: "metal_fences",
        name: "Заборы и ограждения",
        image: "https://images.unsplash.com/photo-1564510714842-1e7b4fa3b942?w=800&q=80",
        items: [
          { name: "Сборка сварного забора", price: "от 550 ₽/п.м" },
          { name: "Забор из сетки", price: "от 550 ₽/п.м" },
          { name: "Монтаж ограждений", price: "от 500 ₽/п.м" },
          { name: "Фундамент под столбы", price: "от 500 ₽/п.м" },
          { name: "Покраска забора", price: "от 60 ₽/м²" },
        ],
      },
      {
        id: "metal_canopies",
        name: "Навесы и козырьки",
        image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
        items: [
          { name: "Навес", price: "от 5 000 ₽/м²" },
          { name: "Навес над крыльцом", price: "от 10 000 ₽" },
          { name: "Козырёк", price: "от 5 000 ₽" },
          { name: "Обшивка", price: "+400–500 ₽/м²" },
        ],
      },
      {
        id: "metal_stairs",
        name: "Лестницы",
        image: "https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80",
        items: [
          { name: "Монтаж лестницы", price: "от 6 700 ₽" },
          { name: "Монтаж деревянной", price: "от 12 700 ₽" },
          { name: "Лестницы под ключ", price: "от 36 700 ₽" },
          { name: "Чердачная лестница", price: "от 4 670 ₽" },
          { name: "Ступени на заказ", price: "от 23 300 ₽" },
          { name: "Отделка маршей", price: "от 1 330 ₽/м²" },
        ],
      },
      {
        id: "metal_gazebo",
        name: "Строительство беседок",
        image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
        items: [
          { name: "Монтаж беседки", price: "от 1 500–2 000 ₽/м²" },
          { name: "Беседка под ключ", price: "от 670 ₽/м²" },
          { name: "Беседка из дерева", price: "от 1 820 ₽/м²" },
        ],
      },
      {
        id: "metal_bathhouse",
        name: "Строительство бань",
        image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80",
        items: [
          { name: "Баня под ключ", price: "от 5 000 ₽/м²" },
          { name: "Каркасная баня", price: "от 5 000 ₽/м²" },
          { name: "Частичное строительство", price: "от 1 270 ₽/м²" },
          { name: "Отделка парной", price: "от 670 ₽/м²" },
          { name: "Массивная баня", price: "от 11 000–12 000 ₽/м²" },
        ],
      },
    ],
  },
];