import { FileText, Home, Phone, Send } from "lucide-react";
import { PHONE, PHONE_DISPLAY } from "../lib/calcData";

const CONTACTS = [{ label: "WhatsApp", href: "https://wa.me/79878377006", icon: Send }, { label: "Telegram", href: "https://t.me/+79063052828", icon: Send }];

export default function About() {
  return <div className="page-shell py-7 sm:py-10">
    <div className="mb-7"><p className="mb-1 text-xs font-mono font-bold uppercase tracking-widest text-primary">О компании</p><h1 className="mb-2 text-3xl font-black text-foreground sm:text-4xl">Решаем Быстро</h1><p className="max-w-2xl text-sm text-muted-foreground">Строительные услуги, ремонт и подготовка строительной документации.</p></div>
    <div className="grid gap-5 md:grid-cols-2"><section className="rb-card rounded-2xl border-2 border-primary/70 bg-card p-6 shadow-sm"><div className="mb-5 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Home className="h-5 w-5" /></div><h2 className="text-xl font-black text-foreground">Ремонт и строительство</h2><ul className="mt-4 space-y-2 text-sm text-muted-foreground"><li>Ремонт квартир</li><li>Отделочные работы</li><li>Строительные работы</li></ul></section><section className="rb-card rounded-2xl border-2 border-primary/70 bg-card p-6 shadow-sm"><div className="mb-5 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><FileText className="h-5 w-5" /></div><h2 className="text-xl font-black text-foreground">Строительная документация</h2><ul className="mt-4 space-y-2 text-sm text-muted-foreground"><li>ППР</li><li>Технологические карты</li><li>Сметы</li><li>ПОС / ПОР</li></ul></section></div>
    <section className="mt-8"><h2 className="mb-5 text-2xl font-black text-foreground sm:text-3xl">Как мы работаем</h2><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">{["Получаем задачу.", "Изучаем исходные материалы.", "Уточняем необходимые данные.", "Выполняем работу.", "Передаём результат."].map((step, index) => <article key={step} className="rb-card rounded-2xl border-2 border-primary/70 bg-card p-5 shadow-sm"><span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-primary text-sm font-black text-white">{index + 1}</span><h3 className="mt-4 text-base font-black text-foreground">{step}</h3></article>)}</div></section>
    <section className="rb-card mt-8 rounded-2xl border-2 border-primary/70 bg-card p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black text-foreground">Контакты</h2><p className="mt-2 text-sm text-muted-foreground">Свяжитесь с нами удобным способом.</p><div className="mt-5 flex flex-wrap gap-3">{CONTACTS.map(({ label, href, icon: Icon }) => <a key={label} href={href} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-primary/70 bg-background px-4 py-2.5 text-sm font-bold text-foreground transition-colors hover:bg-primary/10"><Icon className="h-4 w-4 text-primary" />{label}</a>)}<a href={`tel:${PHONE}`} className="inline-flex items-center gap-2 rounded-xl border border-primary/70 bg-background px-4 py-2.5 text-sm font-bold text-foreground transition-colors hover:bg-primary/10"><Phone className="h-4 w-4 text-primary" />{PHONE_DISPLAY}</a></div></section>
  </div>;
}
