begin;

create extension if not exists pgcrypto;

create sequence if not exists public.order_number_seq
  as bigint
  start with 1047
  increment by 1;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Администратором считается пользователь Supabase Auth с
-- app_metadata.role = "admin". app_metadata назначается только на сервере.
create or replace function public.is_admin()
returns boolean
language sql
stable
set search_path = public
as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin';
$$;

create table if not exists public.orders (
  id text primary key default gen_random_uuid()::text,
  number bigint not null default nextval('public.order_number_seq'),
  title text not null,
  location text not null default '',
  description text not null default '',
  preferred_deadline text not null default '',
  work_subtotal numeric(14,2) not null default 0 check (work_subtotal >= 0),
  materials_subtotal numeric(14,2) not null default 0 check (materials_subtotal >= 0),
  surcharges numeric(14,2) not null default 0 check (surcharges >= 0),
  calculated_cost numeric(14,2) not null default 0 check (calculated_cost >= 0),
  calculated_total numeric(14,2) not null default 0 check (calculated_total >= 0),
  final_total numeric(14,2) not null default 0 check (final_total >= 0),
  total numeric(14,2) not null default 0 check (total >= 0),
  contractor_payment numeric(14,2) not null default 0 check (contractor_payment >= 0),
  client_price numeric(14,2) not null default 0 check (client_price >= 0),
  owner_expenses numeric(14,2) not null default 0 check (owner_expenses >= 0),
  expected_profit numeric(14,2) not null default 0,
  photos text[] not null default '{}'::text[],
  status text not null default 'draft' check (status in ('draft', 'active', 'closed')),
  is_published boolean not null default false,
  is_manual_total boolean not null default false,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_number_unique unique (number),
  constraint orders_publication_state_check check (not is_published or status = 'active')
);

alter sequence public.order_number_seq owned by public.orders.number;

create table if not exists public.order_works (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  work_id text,
  category_id text,
  group_id text,
  title text not null,
  unit text not null default '',
  unit_price numeric(14,2) not null default 0 check (unit_price >= 0),
  quantity numeric(14,3) not null default 0 check (quantity >= 0),
  total_price numeric(14,2) not null default 0 check (total_price >= 0),
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id text primary key default gen_random_uuid()::text,
  client_name text not null default '',
  location text not null default '',
  title text not null,
  description text not null default '',
  deadline text not null default '',
  review text not null default '',
  work_subtotal numeric(14,2) not null default 0 check (work_subtotal >= 0),
  materials_subtotal numeric(14,2) not null default 0 check (materials_subtotal >= 0),
  extra_costs numeric(14,2) not null default 0 check (extra_costs >= 0),
  calculated_total numeric(14,2) not null default 0 check (calculated_total >= 0),
  final_total numeric(14,2) not null default 0 check (final_total >= 0),
  total numeric(14,2) not null default 0 check (total >= 0),
  is_manual_total boolean not null default false,
  is_published boolean not null default false,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_works (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  work_id text,
  category_id text,
  group_id text,
  title text not null,
  unit text not null default '',
  unit_price numeric(14,2) not null default 0 check (unit_price >= 0),
  quantity numeric(14,3) not null default 0 check (quantity >= 0),
  total_price numeric(14,2) not null default 0 check (total_price >= 0),
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_media (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  stage text not null check (stage in ('before', 'process', 'after')),
  src text not null,
  is_cover boolean not null default false,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_documents (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  document_type text not null check (document_type in ('contract', 'act', 'additional')),
  name text not null,
  mime_type text not null default 'application/octet-stream',
  src text not null,
  is_public boolean not null default false,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id text primary key default gen_random_uuid()::text,
  client_name text not null,
  location text not null,
  service_title text not null,
  review_text text not null,
  rating smallint not null default 5 check (rating between 1 and 5),
  photos jsonb not null default '[]'::jsonb check (jsonb_typeof(photos) = 'array'),
  order_number text not null default '',
  contact text not null default '',
  consent boolean not null default false,
  status text not null default 'pending' check (status in ('pending', 'published', 'rejected')),
  is_published boolean not null default false,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reviews_publication_state_check check (is_published = (status = 'published'))
);

create table if not exists public.pricing_overrides (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('calculatorWorks', 'turnkey', 'materials', 'serviceItems', 'serviceCategories')),
  item_id text not null,
  price numeric(14,2) not null check (price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pricing_overrides_scope_item_unique unique (scope, item_id)
);

create unique index if not exists project_media_one_cover_per_project_idx
  on public.project_media(project_id)
  where is_cover;
create index if not exists orders_public_list_idx
  on public.orders(updated_at desc)
  where is_published and status = 'active';
create index if not exists order_works_order_sort_idx
  on public.order_works(order_id, sort_order, id);
create index if not exists projects_public_list_idx
  on public.projects(updated_at desc)
  where is_published;
create index if not exists project_works_project_sort_idx
  on public.project_works(project_id, sort_order, id);
create index if not exists project_media_project_stage_sort_idx
  on public.project_media(project_id, stage, sort_order, id);
create index if not exists project_documents_project_type_sort_idx
  on public.project_documents(project_id, document_type, sort_order, id);
create index if not exists reviews_status_updated_idx
  on public.reviews(status, updated_at desc);

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();
drop trigger if exists order_works_set_updated_at on public.order_works;
create trigger order_works_set_updated_at before update on public.order_works
for each row execute function public.set_updated_at();
drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects
for each row execute function public.set_updated_at();
drop trigger if exists project_works_set_updated_at on public.project_works;
create trigger project_works_set_updated_at before update on public.project_works
for each row execute function public.set_updated_at();
drop trigger if exists project_media_set_updated_at on public.project_media;
create trigger project_media_set_updated_at before update on public.project_media
for each row execute function public.set_updated_at();
drop trigger if exists project_documents_set_updated_at on public.project_documents;
create trigger project_documents_set_updated_at before update on public.project_documents
for each row execute function public.set_updated_at();
drop trigger if exists reviews_set_updated_at on public.reviews;
create trigger reviews_set_updated_at before update on public.reviews
for each row execute function public.set_updated_at();
drop trigger if exists pricing_overrides_set_updated_at on public.pricing_overrides;
create trigger pricing_overrides_set_updated_at before update on public.pricing_overrides
for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_works enable row level security;
alter table public.projects enable row level security;
alter table public.project_works enable row level security;
alter table public.project_media enable row level security;
alter table public.project_documents enable row level security;
alter table public.reviews enable row level security;
alter table public.pricing_overrides enable row level security;

-- Публичное чтение разрешено только для опубликованных записей.
create policy "anon reads published orders"
on public.orders for select to anon
using (is_published and status = 'active');

create policy "anon reads works of published orders"
on public.order_works for select to anon
using (exists (
  select 1 from public.orders
  where orders.id = order_works.order_id
    and orders.is_published
    and orders.status = 'active'
));

create policy "anon reads published projects"
on public.projects for select to anon
using (is_published);

create policy "anon reads works of published projects"
on public.project_works for select to anon
using (exists (
  select 1 from public.projects
  where projects.id = project_works.project_id
    and projects.is_published
));

create policy "anon reads media of published projects"
on public.project_media for select to anon
using (exists (
  select 1 from public.projects
  where projects.id = project_media.project_id
    and projects.is_published
));

create policy "anon reads public documents of published projects"
on public.project_documents for select to anon
using (is_public and exists (
  select 1 from public.projects
  where projects.id = project_documents.project_id
    and projects.is_published
));

create policy "anon reads published reviews"
on public.reviews for select to anon
using (is_published and status = 'published');

-- Аноним может отправить только новый отзыв на модерацию.
-- Права на INSERT ниже не позволяют передать status/is_published/is_demo.
create policy "anon submits pending reviews"
on public.reviews for insert to anon
with check (
  status = 'pending'
  and not is_published
  and not is_demo
  and consent
  and char_length(btrim(client_name)) between 1 and 120
  and char_length(btrim(location)) between 1 and 240
  and char_length(btrim(service_title)) between 1 and 240
  and char_length(btrim(review_text)) between 1 and 5000
  and char_length(contact) <= 500
  and jsonb_array_length(photos) <= 10
);

-- Полный доступ получает только authenticated-пользователь с ролью admin
-- в app_metadata его JWT. Обычный authenticated-пользователь доступа не получает.
create policy "admins manage orders"
on public.orders for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "admins manage order works"
on public.order_works for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "admins manage projects"
on public.projects for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "admins manage project works"
on public.project_works for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "admins manage project media"
on public.project_media for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "admins manage project documents"
on public.project_documents for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "admins manage reviews"
on public.reviews for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "admins manage pricing"
on public.pricing_overrides for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Безопасные публичные представления. Они не включают client_price,
-- owner_expenses, expected_profit и контактные/модерационные поля отзывов.
create or replace view public.published_orders
with (security_invoker = true)
as
select
  o.id,
  o.number,
  o.title,
  o.location,
  o.description,
  o.preferred_deadline,
  o.contractor_payment,
  o.photos,
  o.created_at,
  o.updated_at,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'work_id', ow.work_id,
        'title', ow.title,
        'unit', ow.unit,
        'quantity', ow.quantity
      ) order by ow.sort_order, ow.id
    )
    from public.order_works ow
    where ow.order_id = o.id
  ), '[]'::jsonb) as selected_works
from public.orders o
where o.is_published and o.status = 'active';

create or replace view public.published_projects
with (security_invoker = true)
as
select
  p.id,
  p.client_name,
  p.location,
  p.title,
  p.description,
  p.deadline,
  p.final_total,
  p.total,
  p.created_at,
  p.updated_at,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'work_id', pw.work_id,
        'title', pw.title,
        'unit', pw.unit,
        'unit_price', pw.unit_price,
        'quantity', pw.quantity,
        'total_price', pw.total_price
      ) order by pw.sort_order, pw.id
    )
    from public.project_works pw
    where pw.project_id = p.id
  ), '[]'::jsonb) as works,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'src', pm.src,
        'stage', pm.stage,
        'is_cover', pm.is_cover,
        'sort_order', pm.sort_order
      ) order by pm.sort_order, pm.id
    )
    from public.project_media pm
    where pm.project_id = p.id
  ), '[]'::jsonb) as media,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'name', pd.name,
        'type', pd.mime_type,
        'src', pd.src,
        'document_type', pd.document_type
      ) order by pd.sort_order, pd.id
    )
    from public.project_documents pd
    where pd.project_id = p.id and pd.is_public
  ), '[]'::jsonb) as documents
from public.projects p
where p.is_published;

create or replace view public.published_reviews
with (security_invoker = true)
as
select
  id,
  client_name,
  location,
  service_title,
  review_text,
  rating,
  photos,
  created_at,
  updated_at
from public.reviews
where is_published and status = 'published';

revoke all on table public.orders from anon;
revoke all on table public.order_works from anon;
revoke all on table public.projects from anon;
revoke all on table public.project_works from anon;
revoke all on table public.project_media from anon;
revoke all on table public.project_documents from anon;
revoke all on table public.reviews from anon;
revoke all on table public.pricing_overrides from anon;

-- Column-level grants не дают anon запросить внутренние поля базовых таблиц.
grant select (id, number, title, location, description, preferred_deadline,
  contractor_payment, photos, status, is_published, created_at, updated_at)
on public.orders to anon;
grant select (id, order_id, work_id, title, unit, quantity, sort_order)
on public.order_works to anon;
grant select (id, client_name, location, title, description, deadline,
  final_total, total, is_published, created_at, updated_at)
on public.projects to anon;
grant select (id, project_id, work_id, title, unit, unit_price, quantity,
  total_price, sort_order)
on public.project_works to anon;
grant select (id, project_id, stage, src, is_cover, sort_order)
on public.project_media to anon;
grant select (id, project_id, document_type, name, mime_type, src, is_public, sort_order)
on public.project_documents to anon;
grant select (id, client_name, location, service_title, review_text, rating,
  photos, status, is_published, created_at, updated_at)
on public.reviews to anon;
grant insert (client_name, location, service_title, review_text, rating,
  photos, order_number, contact, consent)
on public.reviews to anon;

grant select on public.published_orders to anon, authenticated;
grant select on public.published_projects to anon, authenticated;
grant select on public.published_reviews to anon, authenticated;

grant all on table public.orders to authenticated;
grant all on table public.order_works to authenticated;
grant all on table public.projects to authenticated;
grant all on table public.project_works to authenticated;
grant all on table public.project_media to authenticated;
grant all on table public.project_documents to authenticated;
grant all on table public.reviews to authenticated;
grant all on table public.pricing_overrides to authenticated;
grant usage, select on sequence public.order_number_seq to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
